"""Generate docs/DATA_CONTRACTS.md from the pydantic schemas.

Usage: python scripts/gen_data_contracts.py
"""

from __future__ import annotations

import sys
import typing
from pathlib import Path

from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from rewind.schemas import (  # noqa: E402
    events,
    features,
    perception,
    risk,
    run,
    simulation,
    validation,
    venue,
    video,
)

MODULES = [
    ("5.1 Video", video),
    ("5.2 Venue", venue),
    ("5.3 Perception", perception),
    ("5.4 Zone features", features),
    ("5.5-5.6 Risk and explanation", risk),
    ("5.7 Events and timeline", events),
    ("5.8 Simulation", simulation),
    ("5.9-5.10 Validation and strategy", validation),
    ("Runs and jobs", run),
]


def _type_str(annotation: object) -> str:
    s = repr(annotation) if not isinstance(annotation, type) else annotation.__name__
    for prefix in ("typing.", "rewind.schemas.", "pydantic.main."):
        s = s.replace(prefix, "")
    for mod in ("video.", "venue.", "perception.", "features.", "risk.", "events.", "simulation.",
                "validation.", "run."):
        s = s.replace(mod, "")
    return s.replace("|", "\\|")


def _models(mod: object) -> list[type[BaseModel]]:
    out = []
    for name in dir(mod):
        obj = getattr(mod, name)
        if (isinstance(obj, type) and issubclass(obj, BaseModel) and obj is not BaseModel
                and obj.__module__ == getattr(mod, "__name__", "")):
            out.append(obj)
    return out


def _literals(mod: object) -> list[tuple[str, tuple[object, ...]]]:
    out = []
    for name in dir(mod):
        obj = getattr(mod, name)
        if typing.get_origin(obj) is typing.Literal:
            out.append((name, typing.get_args(obj)))
    return out


def render() -> str:
    lines = [
        "# Data Contracts",
        "",
        "_Generated by `scripts/gen_data_contracts.py` from `backend/rewind/schemas/`. Do not edit by hand._",
        "",
        "All times are seconds from video start. World coordinates are metres in the venue frame. "
        "IDs are strings. TypeScript mirrors live in `frontend/src/types/` with identical snake_case "
        "field names.",
        "",
    ]
    for title, mod in MODULES:
        lines += [f"## {title}", "", f"Module: `rewind.schemas.{mod.__name__.split('.')[-1]}`", ""]
        for lname, args in _literals(mod):
            lines += [f"**`{lname}`** = " + " \\| ".join(f"`{a!r}`" for a in args), ""]
        for model in _models(mod):
            lines += [f"### `{model.__name__}`", ""]
            doc = (model.__doc__ or "").strip()
            if doc and not doc.startswith("!!!") and "BaseModel" not in doc:
                lines += [doc.splitlines()[0], ""]
            lines += ["| Field | Type | Default |", "|---|---|---|"]
            for fname, f in model.model_fields.items():
                default = "required" if f.is_required() else repr(f.get_default(call_default_factory=True))
                lines.append(f"| `{fname}` | `{_type_str(f.annotation)}` | {default} |")
            lines.append("")
    return "\n".join(lines)


def main() -> None:
    out = ROOT / "docs" / "DATA_CONTRACTS.md"
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
